In [2]:
import theano
from  theano import tensor as T, function

import numpy as np

In [17]:
X = T.matrix('x')  # Variable simbólica
Y = X ** 2
F = function([X], [Y]) # Compilación

In [4]:
x = np.ones((2, 2)) * 3
x

array([[ 3.,  3.],
       [ 3.,  3.]])

In [7]:
y = F(x)
y

[array([[ 9.,  9.],
        [ 9.,  9.]])]

In [8]:
print(x)

[[ 3.  3.]
 [ 3.  3.]]


In [9]:
print(y)

[array([[ 9.,  9.],
       [ 9.,  9.]])]


In [10]:
# Derivadas

Z = T.grad(Y.sum(), X)  # grad es la derivada, en este caso, respecto a 'x'

In [12]:
G = function([X], [Y,Z])

In [13]:
x = np.ones((2, 2))*3
y, z = G(x)

In [14]:
print(x)

[[ 3.  3.]
 [ 3.  3.]]


In [15]:
print(y)

[[ 9.  9.]
 [ 9.  9.]]


In [16]:
print(z)

[[ 6.  6.]
 [ 6.  6.]]
